-- MySQL Script generated by MySQL Workbench
-- Sun Nov 26 13:31:30 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`authentications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`authentications` ;

CREATE TABLE IF NOT EXISTS `mydb`.`authentications` (
  `authentication_id` INT UNSIGNED NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `salt` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`authentication_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `authentication_id` INT UNSIGNED NOT NULL,
  `is_sign_in` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `authentication_id`),
  INDEX `fk_users_authentications1_idx` (`authentication_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_authentications1`
    FOREIGN KEY (`authentication_id`)
    REFERENCES `mydb`.`authentications` (`authentication_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`repositories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`repositories` ;

CREATE TABLE IF NOT EXISTS `mydb`.`repositories` (
  `repository_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`repository_id`, `user_id`),
  INDEX `fk_repositories_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_repositories_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`admins` ;

CREATE TABLE IF NOT EXISTS `mydb`.`admins` (
  `admin_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `authentication_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`admin_id`, `authentication_id`),
  INDEX `fk_admins_authentications1_idx` (`authentication_id` ASC) VISIBLE,
  CONSTRAINT `fk_admins_authentications1`
    FOREIGN KEY (`authentication_id`)
    REFERENCES `mydb`.`authentications` (`authentication_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`groups` ;

CREATE TABLE IF NOT EXISTS `mydb`.`groups` (
  `group_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`group_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roles_in_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`roles_in_groups` ;

CREATE TABLE IF NOT EXISTS `mydb`.`roles_in_groups` (
  `role_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_has_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users_has_groups` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users_has_groups` (
  `user_id` INT UNSIGNED NOT NULL,
  `group_id` INT UNSIGNED NOT NULL,
  `role_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `group_id`, `role_id`),
  INDEX `fk_users_has_groups_groups1_idx` (`group_id` ASC) VISIBLE,
  INDEX `fk_users_has_groups_users_idx` (`user_id` ASC) INVISIBLE,
  INDEX `fk_users_has_groups_roles_in_groups_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_groups_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_groups_groups1`
    FOREIGN KEY (`group_id`)
    REFERENCES `mydb`.`groups` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_groups_roles_in_groups`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`roles_in_groups` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
